# Generated by Django 4.2.27 on 2026-01-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('store', models.CharField(max_length=255)),
                ('card_user', models.CharField(choices=[('me', 'Me'), ('wife', 'Wife'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('burden_type', models.CharField(choices=[('shared', 'Shared'), ('wife_only', 'Wife only'), ('me_only', 'Me only')], default='shared', max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('memo', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('csv_rakuten', 'CSV (Rakuten)'), ('csv_mitsui', 'CSV (Mitsui)'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
    ]
