# Generated by Django 4.2.27 on 2026-01-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payer',
            field=models.CharField(choices=[('me', 'Me'), ('wife', 'Wife'), ('unknown', 'Unknown')], default='me', help_text='実際に支払った人（精算ロジック用）', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='card_user',
            field=models.CharField(blank=True, choices=[('me', 'Me'), ('wife', 'Wife'), ('unknown', 'Unknown')], default='unknown', help_text='誰がこの支出を使ったか（UI表示用）', max_length=10, null=True),
        ),
    ]
