# Generated by Django 4.2.27 on 2026-02-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_payer_alter_expense_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text='店名にこの文字列が含まれていたら除外します', max_length=255)),
                ('target_source', models.CharField(choices=[('all', 'All sources'), ('csv_rakuten', 'Csv Rakuten'), ('csv_mitsui', 'Csv Mitsui')], default='all', help_text='どのソースに適用するか。all なら全 CSV に適用。', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['keyword', 'id'],
            },
        ),
    ]
