# Generated by Django 4.2.27 on 2026-02-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_exclusionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('uncategorized', '未分類'), ('food', '食費'), ('daily', '日用品'), ('outside_food', '外食'), ('utility', '光熱費'), ('travel', '旅行'), ('other', 'その他')], default='uncategorized', max_length=32),
        ),
    ]
