# Generated by Django 4.2.27 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expense_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("excluded_words", models.JSONField(blank=True, default=list)),
                ("highlight_threshold", models.PositiveIntegerField(default=10000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App settings",
                "verbose_name_plural": "App settings",
            },
        ),
    ]
